### ISSUE TITLE
Add functionality to read, edit, write artifacts

### ISSUE THREAD

**Issue by joachimmetz** [ForensicArtifacts/artifacts#183]
Per request by @pidydx 

Add functionality to read, edit, write artifacts

**Comment by pidydx** [comment]
At the moment the artifact server I am working on will leave the editing up to the UI side and just submit a modified JSON object back to the server where it overwrites the previous definition (assuming it validates and does not have conflicts).

I still need to work out proper validation for artifact groups.  When they get imported or the db initialized they get validated properly due to being read out of a file that contains all the other artifacts.  I haven't done anything to ensure that an artifact group will properly validate if submitted alone if the server already has copies of the necessary artifacts.

**Comment by pidydx** [comment]
I am very close to a 0.0.1 API only release (hopefully within the next week) to start sharing for feedback.  Just making sure all the basics of the API are covered as a starting point.

**Comment by joachimmetz** [comment]
Does not appear this is priority, closing issue
